{% set name = "wlogdate" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/e4/cc/1bc73b2458f2519d4b1bedc37267c4e5f4c5947af5ef0af32b3f4aab123a/wLogDate-1.0.2.tar.gz"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - bitsets
    - dendropy >=4.3.0
    - numpy >=1.18.5
    - pip
    - python
    - scipy >=1.3.1
  run:
    - bitsets
    - dendropy >=4.3.0
    - numpy >=1.18.5
    - python
    - scipy >=1.3.1

test:
  imports:
    - logdate

about:
  home: "The package home page"
  license: "GNU General Public (GPL)"
  license_family: "LGPL"
  license_file: ""
  summary: "Log Transformation Improves Dating of Phylogenies"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
